'''
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
'''


class Solution:

    #         abcdabcde
    #         abcdeabecd
    #
    #         1. dict Time O(N), Space O(N) -> O(1), since there is only 26 chars
    #         2. sorted and compare. Time O(NlogN) Space O(N) -> O(1), can sort in place in Python
    #         3. bit manipulation. TimeO(N) Space O(1)
    #                 a XOR a = 0
    #                 so only one char left

    # Time O(N) Space O(1), runtime = 36 ms
    def findTheDifference(self, s: str, t: str) -> str:
        char = 0
        for i in range(len(s)):
            char ^= ord(s[i]) ^ ord(t[i])

        char ^= ord(t[-1])
        return chr(char)